// Auto-generated by scripts/discover-backend-plugins.js
// DO NOT EDIT MANUALLY

#[path = "../../../../plugins/dashboard/mod.rs"]
pub mod dashboard;
#[path = "../../../../plugins/database/mod.rs"]
pub mod database;
#[path = "../../../../plugins/philips_hue/mod.rs"]
pub mod philips_hue;
#[path = "../../../../plugins/plugin_ide/mod.rs"]
pub mod plugin_ide;
#[path = "../../../../plugins/system/mod.rs"]
pub mod system;
#[path = "../../../../plugins/twitch/mod.rs"]
pub mod twitch;
#[path = "../../../../plugins/withings/mod.rs"]
pub mod withings;

use crate::bridge::core::plugin_manager::PluginManager;

/// Auto-generated plugin registration function
pub fn register_all_plugins(manager: &mut PluginManager) {
    log::info!("📦 Registering 7 auto-discovered plugins...");

    // Tier 0: Core plugins
    manager.register(database::DatabasePlugin);

    // Tier 3+: Other plugins
    manager.register(dashboard::DashboardPlugin);
    manager.register(philips_hue::PhilipsHuePlugin);
    manager.register(plugin_ide::PluginIdePlugin);
    manager.register(system::SystemPlugin);
    manager.register(twitch::TwitchPlugin);
    manager.register(withings::WithingsPlugin);

    log::info!("✅ Plugin registration complete (7 plugins)");
}
