// Auto-generated by scripts/discover-backend-plugins.js
// DO NOT EDIT MANUALLY

#[path = "../../../../plugins/database/mod.rs"]
pub mod database;
#[path = "../../../../plugins/status/mod.rs"]
pub mod status;
#[path = "../../../../plugins/system/mod.rs"]
pub mod system;
#[path = "../../../../plugins/twitch/mod.rs"]
pub mod twitch;

use crate::bridge::core::plugin_manager::PluginManager;

/// Auto-generated plugin registration function
pub fn register_all_plugins(manager: &mut PluginManager) {
    log::info!("📦 Registering 4 auto-discovered plugins...");

    // Tier 0: Core plugins
    manager.register(database::DatabasePlugin);

    // Tier 3+: Other plugins
    manager.register(status::StatusPlugin);
    manager.register(system::SystemPlugin);
    manager.register(twitch::TwitchPlugin);

    log::info!("✅ Plugin registration complete (4 plugins)");
}
