// Auto-generated by scripts/discover-backend-plugins.js
// DO NOT EDIT MANUALLY

#[path = "../../../plugins/alerts/mod.rs"]
pub mod alerts;
#[path = "../../../plugins/alexa/mod.rs"]
pub mod alexa;
#[path = "../../../plugins/auction/mod.rs"]
pub mod auction;
#[path = "../../../plugins/channel_commands/mod.rs"]
pub mod channel_commands;
#[path = "../../../plugins/confessions/mod.rs"]
pub mod confessions;
#[path = "../../../plugins/counters/mod.rs"]
pub mod counters;
#[path = "../../../plugins/currency/mod.rs"]
pub mod currency;
#[path = "../../../plugins/database/mod.rs"]
pub mod database;
#[path = "../../../plugins/discord/mod.rs"]
pub mod discord;
#[path = "../../../plugins/files/mod.rs"]
pub mod files;
#[path = "../../../plugins/followers/mod.rs"]
pub mod followers;
#[path = "../../../plugins/goals/mod.rs"]
pub mod goals;
#[path = "../../../plugins/household/mod.rs"]
pub mod household;
#[path = "../../../plugins/hue/mod.rs"]
pub mod hue;
#[path = "../../../plugins/layouts/mod.rs"]
pub mod layouts;
#[path = "../../../plugins/levels/mod.rs"]
pub mod levels;
#[path = "../../../plugins/mood_tracker/mod.rs"]
pub mod mood_tracker;
#[path = "../../../plugins/notes/mod.rs"]
pub mod notes;
#[path = "../../../plugins/overlay_manager/mod.rs"]
pub mod overlay_manager;
#[path = "../../../plugins/overlays/mod.rs"]
pub mod overlays;
#[path = "../../../plugins/packs/mod.rs"]
pub mod packs;
#[path = "../../../plugins/roulette/mod.rs"]
pub mod roulette;
#[path = "../../../plugins/song_requests/mod.rs"]
pub mod song_requests;
#[path = "../../../plugins/status/mod.rs"]
pub mod status;
#[path = "../../../plugins/system/mod.rs"]
pub mod system;
#[path = "../../../plugins/test_plugin/mod.rs"]
pub mod test_plugin;
#[path = "../../../plugins/text_commands/mod.rs"]
pub mod text_commands;
#[path = "../../../plugins/ticker/mod.rs"]
pub mod ticker;
#[path = "../../../plugins/timer/mod.rs"]
pub mod timer;
#[path = "../../../plugins/todos/mod.rs"]
pub mod todos;
#[path = "../../../plugins/tts/mod.rs"]
pub mod tts;
#[path = "../../../plugins/twitch/mod.rs"]
pub mod twitch;
#[path = "../../../plugins/user_profiles/mod.rs"]
pub mod user_profiles;
#[path = "../../../plugins/watchtime/mod.rs"]
pub mod watchtime;
#[path = "../../../plugins/wheel/mod.rs"]
pub mod wheel;
#[path = "../../../plugins/withings/mod.rs"]
pub mod withings;
#[path = "../../../plugins/youtube/mod.rs"]
pub mod youtube;

use crate::core::plugin_manager::PluginManager;

/// Auto-generated plugin registration function
pub fn register_all_plugins(manager: &mut PluginManager) {
    log::info!("📦 Registering 37 auto-discovered plugins...");

    // Tier 0: Core plugins
    manager.register(database::DatabasePlugin);

    // Tier 1: Foundational plugins
    manager.register(counters::CountersPlugin);
    manager.register(currency::CurrencyPlugin);
    manager.register(goals::GoalsPlugin);
    manager.register(notes::NotesPlugin);
    manager.register(todos::TodosPlugin);

    // Tier 2: Game plugins
    manager.register(auction::AuctionPlugin);
    manager.register(levels::LevelsPlugin);
    manager.register(packs::PacksPlugin);
    manager.register(roulette::RoulettePlugin);
    manager.register(wheel::WheelPlugin);

    // Tier 3+: Other plugins
    manager.register(alerts::AlertsPlugin);
    manager.register(alexa::AlexaPlugin);
    manager.register(channel_commands::ChannelCommandsPlugin);
    manager.register(confessions::ConfessionsPlugin);
    manager.register(discord::DiscordPlugin);
    manager.register(files::FilesPlugin);
    manager.register(followers::FollowersPlugin);
    manager.register(household::HouseholdPlugin);
    manager.register(hue::HuePlugin);
    manager.register(layouts::LayoutsPlugin);
    manager.register(mood_tracker::MoodTrackerPlugin);
    manager.register(overlay_manager::OverlayManagerPlugin);
    manager.register(overlays::OverlaysPlugin);
    manager.register(song_requests::SongRequestsPlugin);
    manager.register(status::StatusPlugin);
    manager.register(system::SystemPlugin);
    manager.register(test_plugin::TestPluginPlugin);
    manager.register(text_commands::TextCommandsPlugin);
    manager.register(ticker::TickerPlugin);
    manager.register(timer::TimerPlugin);
    manager.register(tts::TtsPlugin);
    manager.register(twitch::TwitchPlugin);
    manager.register(user_profiles::UserProfilesPlugin);
    manager.register(watchtime::WatchtimePlugin);
    manager.register(withings::WithingsPlugin);
    manager.register(youtube::YoutubePlugin);

    log::info!("✅ Plugin registration complete (37 plugins)");
}
